# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Outfit7' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Outfit7
   pod 'SnapKit'
   pod 'SwiftLint'

  target 'Outfit7Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Outfit7UITests' do
    # Pods for testing
  end

end
